name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all
          
permissions:
  contents: read
  pages: write
  id-token: write         

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
        
      # Скачивание истории отчетов Allure
      - name: Download Allure history
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: allure-results/history
        
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
        
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
        
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results 
        continue-on-error: true
        
      - name: Run extended tests
        if: "github.event.inputs.deployment_target == 'extended'" 
        run: pytest -m extended --alluredir=allure-results
        continue-on-error: true

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz && sudo tar -zxvf allure-2.30.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
        
      # Генерация отчета с учетом истории
      - name: Generate report with history
        run: allure generate allure-results --clean -o _site
        
      # Сохранение Allure отчета и истории
      - name: Upload Allure report and history
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: _site
          retention-days: 1
          
      - name: Upload Allure history
        uses: actions/upload-artifact@v3
        with:
          name: allure-history
          path: _site/history
          retention-days: 1
          
  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: _site
      
      # Публикация на GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
