name: CI Pipeline with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг для клонирования репозитория
    - name: Checkout code
      uses: actions/checkout@v2

    # Шаг для установки Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Запуск тестов и сохранение результатов в allure-results
    - name: Run tests with pytest
      run: |
        pytest --alluredir=allure-results

    # Загрузка результатов Allure в качестве артефакта
    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Загрузка предыдущих результатов Allure
    - name: Download previous Allure results
      uses: actions/download-artifact@v3
      with:
        name: allure-results-history
        path: previous-allure-results/

        
    # Генерация Allure отчета
    - name: Generate Allure report
      run: |
        allure generate Allure results -o allure-report


    # Загрузка отчета Allure в качестве артефакта
    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    # Загрузка истории Allure
    - name: Upload allure-results-history
      uses: actions/upload-artifact@v3
      with:
        name: allure-results-history
        path: allure-results-history/history/
