name: CI Pipeline with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --alluredir=allure-results

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Download previous Allure results
      uses: actions/download-artifact@v3
      with:
        name: allure-results
        path: previous-allure-results/

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.tgz
        tar -zxvf allure-2.22.1.tgz
        sudo mv allure-2.22.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Prepare Allure history
      run: |
        mkdir -p allure-history
        if [ -d previous-allure-results/history ]; then
          cp -r previous-allure-results/history/* allure-history/
        fi

    - name: Combine previous and current Allure results
      run: |
        mkdir -p combined-allure-results
        if [ -d previous-allure-results ] && [ "$(ls -A previous-allure-results)" ]; then
          cp -r previous-allure-results/* combined-allure-results/
        fi
        if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
          cp -r allure-results/* combined-allure-results/
        fi

    - name: Generate Allure report
      run: |
        allure generate combined-allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    - name: Upload Allure history
      run: |
        if [ -d allure-history ] && [ "$(ls -A allure-history)" ]; then
          echo "Uploading Allure history..."
          # Use upload-artifact here instead of run
          echo "Uploading allure history..."
        else
          echo "No Allure history to upload."
          exit 0
        fi

    - name: Upload Allure history artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-history
        path: allure-history/
        
    - name: Check if report archive exists
      run: |
        if [ -f allure-report.tgz ]; then
          echo "Report archive found. Extracting..."
          tar -zxvf allure-report.tgz -C ./allure-history
        else
          echo "No report archive found."
        fi
