name: CI Pipeline with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --alluredir=allure-results

    - name: List uploaded allure results
      run: |
        echo "Artifacts uploaded:"
        ls -la allure-results/

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Create previous allure results directory
      run: |
        mkdir -p previous-allure-results

    - name: Download previous Allure history
      uses: actions/download-artifact@v3
      with:
        name: allure-results
        path: previous-allure-results/

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.tgz
        tar -zxvf allure-2.22.1.tgz
        sudo mv allure-2.22.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: List previous allure results
      run: |
        ls -la previous-allure-results/

    - name: List contents of current allure results
      run: |
        ls -la allure-results/

    - name: Combine previous and current Allure results
      run: |
        mkdir -p combined-allure-results
        if [ -d previous-allure-results ] && [ "$(ls -A previous-allure-results)" ]; then
          cp -r previous-allure-results/* combined-allure-results/
        fi
        if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
          cp -r allure-results/* combined-allure-results/
        fi

    - name: List contents of combined allure results
      run: |
        ls -la combined-allure-results/

    - name: Generate Allure report
      run: |
        allure generate combined-allure-results -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    - name: Upload Allure history
      uses: actions/upload-artifact@v3
      with:
        name: allure-history
        path: combined-allure-results/history/
