jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4

      # Скачивание истории отчетов Allure
      - name: Download Allure history
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: allure-results/history
        continue-on-error: true  # Продолжить, если артефакт не найден

      # Если истории нет, создайте папку для неё
      - name: Create history folder if missing
        run: mkdir -p allure-results/history

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz && sudo tar -zxvf allure-2.30.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
        
      # Генерация отчета с учетом истории
      - name: Generate report with history
        run: allure generate allure-results --clean -o _site

      # Сохранение Allure отчета и истории
      - name: Upload Allure report and history
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: _site

      - name: Upload Allure history
        uses: actions/upload-artifact@v3
        with:
          name: allure-history
          path: _site/history
