name: Python autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - all
          - smoke
          - regression
          - extended

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests

    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create allure-results directory
        run: mkdir -p allure-results

      - name: Check allure-results directory
        run: |
          echo "Contents of allure-results directory before downloading history:"
          ls -R allure-results

      - name: Download previous Allure history
        uses: actions/download-artifact@v3
        with:
          name: allure-history-${{ github.run_id }}  # Используйте уникальное имя
          path: allure-results/history
        continue-on-error: true  # Позволяет продолжить, даже если артефакт не найден

      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results

      # Другие шаги...

      - name: Upload allure-results with history
        uses: actions/upload-artifact@v3
        with:
          name: allure-history-${{ github.run_id }}  # Уникальное имя артефакта
          path: allure-results/history
          retention-days: 7

  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Sleep before downloading artifacts
        run: sleep 10  # Задержка перед загрузкой

      - name: Download Allure report artifact
        uses: actions/download-artifact@v3
        with:
          name: allure-report  # Убедитесь, что имя соответствует загруженному артефакту
          path: allure-report

      # Другие шаги...
