name: CI Pipeline with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг для клонирования репозитория
    - name: Checkout code
      uses: actions/checkout@v2

    # Шаг для установки Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Запуск тестов и сохранение результатов в allure-results
    - name: Run tests with pytest
      run: |
        pytest --alluredir=allure-results

    # Загрузка результатов Allure в качестве артефакта
    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Загрузка предыдущих результатов Allure
    - name: Download previous Allure results
      uses: actions/download-artifact@v3
      with:
        name: allure-results
        path: previous-allure-results/

    # Шаг для клонирования репозитория
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # Установка Allure для генерации отчетов
    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.22.1/allure-2.22.1.tgz
        tar -zxvf allure-2.22.1.tgz
        sudo mv allure-2.22.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    # Подготовка истории Allure
    - name: Prepare Allure history
      run: |
        mkdir -p allure-history
        # Копирование истории из предыдущих результатов, если она существует
        if [ -d previous-allure-results/history ]; then
          cp -r previous-allure-results/history/* allure-history/
        fi

    # Объединение предыдущих и текущих результатов Allure
    - name: Combine previous and current Allure results
      run: |
        mkdir -p combined-allure-results
        if [ -d previous-allure-results ] && [ "$(ls -A previous-allure-results)" ]; then
          cp -r previous-allure-results/* combined-allure-results/
        fi
        if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
          cp -r allure-results/* combined-allure-results/
        fi

    # Копирование истории в объединенные результаты
    - name: Copy history to combined results
      run: |
        if [ -d allure-history ] && [ "$(ls -A allure-history)" ]; then
          cp -r allure-history/* combined-allure-results/history/
        fi

    # Генерация Allure отчета
    - name: Generate Allure report
      run: |
        allure generate combined-allure-results -o allure-report

    # Загрузка отчета Allure в качестве артефакта
    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    # Загрузка истории Allure
    # - name: Upload combined-allure-results
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: combined-allure-results
    #     path: combined-allure-results/history/
